[package]
name = "xbpatch-gui"
version = "0.1.0"
edition = "2024"

[dependencies]
xbpatch-core = { path = "../core" }

serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"

eframe = "0.32.1"
env_logger = "0.11.8"

walkdir = "2.5.0"

dirs-next = "2.0.0"
