name: Rust

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*.*.*' # eg v1.0.0, v2.1.5
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BUILD_TARGET: [release] # refers to a cargo profile
    steps:
    - uses: actions/checkout@v5
    - name: Build binaries in "${{ matrix.BUILD_TARGET }}" mode
      run: cargo build --profile ${{ matrix.BUILD_TARGET }}
    - name: Run tests in "${{ matrix.BUILD_TARGET }}" mode
      run: cargo test --profile ${{ matrix.BUILD_TARGET }}
    - name: Clone repo
    - uses: actions/checkout@v4
    - name: Cache
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}  
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    outputs:
      release_built: ${{ steps.set-output.outputs.release_built }}
